### ISSUE TITLE
seq.sequence~ does not respond to lists

### ISSUE THREAD

**Issue by wetterberg** [pdmeyer/seq#2]
it uses the first member repeatedly instead

**Comment by wetterberg** [comment]
user error, I guess?

**Comment by pdmeyer** [comment]
can you paste your patch (copy compressed) here? 

running a quick test in seq.sequence~.maxhelp i'm not seeing that issue.

**Comment by wetterberg** [comment]
no, I mean i misunderstood the general setup - like, is the intention that seq.rprob~drive seq.sequence~? because it "inits" with a list, but is only getting 1s.

**Comment by pdmeyer** [comment]
ah yes

so seq.sequence~ wants what I call a counter - basically a stepped signal where the value indicate a "slot" to play back. very similar to [stash~ @mode 1]

what seq.rprob~ outputs from its 1st inlet depends on its `outputmode`, which is set to `gate` by default. if you change that to something else like `event_ix`, you'll see that it will output values other than 1 and traverse through the sequence stored in seq.sequence~

**Comment by wetterberg** [comment]
Ah, so that part is missing from the main Seq overview example ;) it fixed the issue.

**Comment by pdmeyer** [comment]
nice find, i'll fix. i'm gonna also make it so that rprob outputs a counter by default instead of the gate. that's what most of the pattern modules do and makes sense

**Comment by pdmeyer** [comment]
fixed https://github.com/pdmeyer/seq/commit/5968c86f44152fc3bbc8dc66d268130846895aab 

event_count is now the default outputmode for rprob
